version: '3'

services:
  web-app:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/project
    command: >
      sh -c "python server/manage.py runserver 0.0.0.0:8000"
    environment:
      TZ: Europe/Moscow

  celery_worker:
    build: .
    container_name: celery_worker
    command: ./scripts/start_celery_worker.sh
    links:
      - redis
    volumes:
      - .:/project
    depends_on:
      - redis

  celery_beat:
    build: .
    container_name: celery_beat
    command: ./scripts/start_celery_beat.sh
    links:
      - redis
    volumes:
      - .:/project
    depends_on:
      - celery_worker
      - redis

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --dir /data --save 60 1 --loglevel warning

volumes:
  redis_data:
